#ifndef MATIOWRAPPER_GLOBAL_H
#define MATIOWRAPPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MATIOWRAPPER_LIBRARY)
#  define MATIOWRAPPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MATIOWRAPPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MATIOWRAPPER_GLOBAL_H
